# Experimentation

In [1]:
from rstt import Ranking
from rstt.stypes import SPlayer
import pandas as pd
from scipy import stats

def evaluate(data: pd.DataFrame, reference: Ranking, trained: Ranking, population: list[SPlayer], percentiles: list[int]=[5, 10, 50]):
    row = {}
    
    # rank correlation
    row['KendallTau'] = stats.kendalltau(reference[population], trained[population]).statistic

    # rank difference
    rank_diffs = [reference[p]- trained[p] for p in population]
    row['Overrate'] = abs(min(rank_diffs))
    row['Underrate'] = max(rank_diffs)

    # accuracy
    for percentile in percentiles:
        threshold = max(int(len(population) // (100/percentile)), 1)
        row[f'{percentile}pr accuracy'] = len(set(reference[:threshold]).intersection(set(trained[:threshold]))) / threshold

    data = pd.concat([data, pd.DataFrame([row])], axis=0, ignore_index=True)
    return data

In [2]:
from rstt import BasicPlayer, BasicElo, LogSolver, BTRanking, RoundRobin

from simulation import settings, experiments, metrics

# parameters
samples = 100
NBPlayers = 60

# data 
COLUMNS = ['KendallTau', 'Underrate', 'Overrate', '5pr accuracy', '10pr accuracy', '50pr accuracy']
RESULTS: dict[str, pd.DataFrame] = {}

exp_name = 'FullRoundRobin'
RESULTS[exp_name] = pd.DataFrame(columns=COLUMNS, dtype='float')
for i in range(samples):
    # test ranking
    elo = BasicElo(f'Elo-{exp_name}')
    
    # simulation model
    model = settings.baseModel(region=1, nb=NBPlayers)
    
    # data set production
    data = experiments.regional_round_robins(f'{exp_name}-Round-Robin',
                                             seeding=model.groundtruth,
                                             population=[model.ecosystem.teams()],
                                             solver=model.solver)
    # elo update
    elo.update(**data)

    # analysis
    RESULTS[exp_name] = evaluate(RESULTS[exp_name], model.groundtruth, elo, model.groundtruth.players())

# show summary
RESULTS[exp_name].describe()

,KendallTau,Underrate,Overrate,5pr accuracy,10pr accuracy,50pr accuracy
count,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000
mean,0.899638,8.580000,8.850000,0.803333,0.880000,0.945000
std,0.015023,2.270496,2.495956,0.195889,0.103475,0.026538
min,0.854237,5.000000,5.000000,0.333333,0.666667,0.900000
25%,0.889266,7.000000,7.000000,0.666667,0.833333,0.933333
50%,0.900565,8.000000,8.000000,0.666667,0.833333,0.933333
75%,0.911864,10.000000,10.000000,1.000000,1.000000,0.966667
max,0.937853,16.000000,17.000000,1.000000,1.000000,1.000000

In [3]:
from project import scene

exp_name = 'Regions'

# store metrics
for region in scene.Region:
    RESULTS[f'{exp_name}-{region}'] = pd.DataFrame(columns=COLUMNS, dtype='float')
RESULTS[exp_name]  = pd.DataFrame(columns=COLUMNS, dtype='float')

for i in range(samples):
    elo2 = BasicElo(f'Elo-{exp_name}')
    
    model = settings.baseModel(len(scene.Region), 10)
    data = experiments.regional_round_robins(f'{exp_name}-Round-Robin',
                                             seeding=model.groundtruth,
                                             population=[model.ecosystem.teams(region) for region in model.ecosystem.regions()],
                                             solver=model.solver)
    elo2.update(**data)
    
    # analysis
    for region in model.ecosystem.regions():
        RESULTS[f'{exp_name}-{region}'] = evaluate(RESULTS[f'{exp_name}-{region}'], model.groundtruth, elo2, model.ecosystem.teams(region))
    RESULTS[exp_name]  = evaluate(RESULTS[exp_name], model.groundtruth, elo2, model.ecosystem.teams())

# show summary
RESULTS[exp_name].describe()

,KendallTau,Underrate,Overrate,5pr accuracy,10pr accuracy,50pr accuracy
count,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000
mean,0.698429,21.430000,20.550000,0.410000,0.618333,0.850667
std,0.045061,4.740232,4.678286,0.236202,0.136690,0.049799
min,0.572881,11.000000,12.000000,0.000000,0.166667,0.733333
25%,0.671751,18.000000,17.000000,0.333333,0.500000,0.825000
50%,0.700565,21.000000,20.000000,0.333333,0.666667,0.866667
75%,0.730226,24.000000,24.000000,0.666667,0.666667,0.866667
max,0.805650,33.000000,36.000000,0.666667,1.000000,0.966667

In [4]:
exp_name = 'SkilledRegions'

for region in scene.Region:
    RESULTS[f'{exp_name}-{region}'] = pd.DataFrame(columns=COLUMNS, dtype='float')
RESULTS[exp_name]  = pd.DataFrame(columns=COLUMNS, dtype='float')

for i in range(samples):
    # test ranking
    elo3 = BasicElo(f'Elo-{exp_name}')
    
    # simulation model
    model = settings.regionalSkills(region=len(scene.Region),
                                    nb=10,
                                    mus=[val for val in range(750, 2500, 250)],
                                    sigmas=[300  for _ in scene.Region])
    
    # data set production
    data = experiments.regional_round_robins(f'{exp_name}-Round-Robin',
                                             seeding=model.groundtruth,
                                             population=[model.ecosystem.teams(region) for region in model.ecosystem.regions()],
                                             solver=model.solver)
    # elo update
    elo3.update(**data)

    # analysis
    for region in scene.Region:
        RESULTS[f'{exp_name}-{region}'] = evaluate(RESULTS[f'{exp_name}-{region}'], model.groundtruth, elo3, model.ecosystem.teams(region))
    RESULTS[exp_name]  = evaluate(RESULTS[exp_name], model.groundtruth, elo3, model.groundtruth.players())

# show summary
RESULTS[exp_name].describe()

,KendallTau,Underrate,Overrate,5pr accuracy,10pr accuracy,50pr accuracy
count,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000
mean,0.321028,38.170000,38.460000,0.290000,0.340000,0.637000
std,0.041582,4.357868,3.909119,0.220473,0.143939,0.049892
min,0.222599,27.000000,29.000000,0.000000,0.000000,0.500000
25%,0.293785,35.750000,35.000000,0.000000,0.291667,0.600000
50%,0.316949,38.000000,38.000000,0.333333,0.333333,0.633333
75%,0.352260,41.000000,41.000000,0.333333,0.500000,0.666667
max,0.412429,49.000000,48.000000,1.000000,0.666667,0.800000

In [5]:
RESULTS[f'{exp_name}-{scene.Region.LEC}'].describe()

,KendallTau,Underrate,Overrate,5pr accuracy,10pr accuracy,50pr accuracy
count,100.000000,100.00000,100.000000,100.000000,100.000000,100.000000
mean,0.720889,20.36000,9.580000,0.110000,0.110000,0.316000
std,0.136085,4.65262,4.219196,0.314466,0.314466,0.150903
min,0.155556,9.00000,1.000000,0.000000,0.000000,0.000000
25%,0.644444,17.75000,7.000000,0.000000,0.000000,0.200000
50%,0.733333,20.00000,10.000000,0.000000,0.000000,0.400000
75%,0.822222,24.00000,12.000000,0.000000,0.000000,0.400000
max,0.911111,30.00000,18.000000,1.000000,1.000000,0.600000